/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as FuncionalidadesRouteImport } from './routes/funcionalidades'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogOrdemServicoSstRouteImport } from './routes/blog.ordem-servico-sst'
import { Route as BlogMobilizacaoTerceirosRouteImport } from './routes/blog.mobilizacao-terceiros'
import { Route as BlogGestaoTreinamentosSstRouteImport } from './routes/blog.gestao-treinamentos-sst'
import { Route as BlogDdsDigitalRouteImport } from './routes/blog.dds-digital'
import { Route as BlogControleAsoRouteImport } from './routes/blog.controle-aso'
import { Route as BlogAprDigitalRouteImport } from './routes/blog.apr-digital'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionalidadesRoute = FuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogOrdemServicoSstRoute = BlogOrdemServicoSstRouteImport.update({
  id: '/blog/ordem-servico-sst',
  path: '/blog/ordem-servico-sst',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogMobilizacaoTerceirosRoute =
  BlogMobilizacaoTerceirosRouteImport.update({
    id: '/blog/mobilizacao-terceiros',
    path: '/blog/mobilizacao-terceiros',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogGestaoTreinamentosSstRoute =
  BlogGestaoTreinamentosSstRouteImport.update({
    id: '/blog/gestao-treinamentos-sst',
    path: '/blog/gestao-treinamentos-sst',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDdsDigitalRoute = BlogDdsDigitalRouteImport.update({
  id: '/blog/dds-digital',
  path: '/blog/dds-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogControleAsoRoute = BlogControleAsoRouteImport.update({
  id: '/blog/controle-aso',
  path: '/blog/controle-aso',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAprDigitalRoute = BlogAprDigitalRouteImport.update({
  id: '/blog/apr-digital',
  path: '/blog/apr-digital',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/termos': typeof TermosRoute
  '/blog/apr-digital': typeof BlogAprDigitalRoute
  '/blog/controle-aso': typeof BlogControleAsoRoute
  '/blog/dds-digital': typeof BlogDdsDigitalRoute
  '/blog/gestao-treinamentos-sst': typeof BlogGestaoTreinamentosSstRoute
  '/blog/mobilizacao-terceiros': typeof BlogMobilizacaoTerceirosRoute
  '/blog/ordem-servico-sst': typeof BlogOrdemServicoSstRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/termos': typeof TermosRoute
  '/blog/apr-digital': typeof BlogAprDigitalRoute
  '/blog/controle-aso': typeof BlogControleAsoRoute
  '/blog/dds-digital': typeof BlogDdsDigitalRoute
  '/blog/gestao-treinamentos-sst': typeof BlogGestaoTreinamentosSstRoute
  '/blog/mobilizacao-terceiros': typeof BlogMobilizacaoTerceirosRoute
  '/blog/ordem-servico-sst': typeof BlogOrdemServicoSstRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/termos': typeof TermosRoute
  '/blog/apr-digital': typeof BlogAprDigitalRoute
  '/blog/controle-aso': typeof BlogControleAsoRoute
  '/blog/dds-digital': typeof BlogDdsDigitalRoute
  '/blog/gestao-treinamentos-sst': typeof BlogGestaoTreinamentosSstRoute
  '/blog/mobilizacao-terceiros': typeof BlogMobilizacaoTerceirosRoute
  '/blog/ordem-servico-sst': typeof BlogOrdemServicoSstRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/faq'
    | '/funcionalidades'
    | '/precos'
    | '/privacidade'
    | '/seguranca'
    | '/termos'
    | '/blog/apr-digital'
    | '/blog/controle-aso'
    | '/blog/dds-digital'
    | '/blog/gestao-treinamentos-sst'
    | '/blog/mobilizacao-terceiros'
    | '/blog/ordem-servico-sst'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/faq'
    | '/funcionalidades'
    | '/precos'
    | '/privacidade'
    | '/seguranca'
    | '/termos'
    | '/blog/apr-digital'
    | '/blog/controle-aso'
    | '/blog/dds-digital'
    | '/blog/gestao-treinamentos-sst'
    | '/blog/mobilizacao-terceiros'
    | '/blog/ordem-servico-sst'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/faq'
    | '/funcionalidades'
    | '/precos'
    | '/privacidade'
    | '/seguranca'
    | '/termos'
    | '/blog/apr-digital'
    | '/blog/controle-aso'
    | '/blog/dds-digital'
    | '/blog/gestao-treinamentos-sst'
    | '/blog/mobilizacao-terceiros'
    | '/blog/ordem-servico-sst'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  FuncionalidadesRoute: typeof FuncionalidadesRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SegurancaRoute: typeof SegurancaRoute
  TermosRoute: typeof TermosRoute
  BlogAprDigitalRoute: typeof BlogAprDigitalRoute
  BlogControleAsoRoute: typeof BlogControleAsoRoute
  BlogDdsDigitalRoute: typeof BlogDdsDigitalRoute
  BlogGestaoTreinamentosSstRoute: typeof BlogGestaoTreinamentosSstRoute
  BlogMobilizacaoTerceirosRoute: typeof BlogMobilizacaoTerceirosRoute
  BlogOrdemServicoSstRoute: typeof BlogOrdemServicoSstRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades': {
      id: '/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof FuncionalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ordem-servico-sst': {
      id: '/blog/ordem-servico-sst'
      path: '/blog/ordem-servico-sst'
      fullPath: '/blog/ordem-servico-sst'
      preLoaderRoute: typeof BlogOrdemServicoSstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mobilizacao-terceiros': {
      id: '/blog/mobilizacao-terceiros'
      path: '/blog/mobilizacao-terceiros'
      fullPath: '/blog/mobilizacao-terceiros'
      preLoaderRoute: typeof BlogMobilizacaoTerceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/gestao-treinamentos-sst': {
      id: '/blog/gestao-treinamentos-sst'
      path: '/blog/gestao-treinamentos-sst'
      fullPath: '/blog/gestao-treinamentos-sst'
      preLoaderRoute: typeof BlogGestaoTreinamentosSstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/dds-digital': {
      id: '/blog/dds-digital'
      path: '/blog/dds-digital'
      fullPath: '/blog/dds-digital'
      preLoaderRoute: typeof BlogDdsDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/controle-aso': {
      id: '/blog/controle-aso'
      path: '/blog/controle-aso'
      fullPath: '/blog/controle-aso'
      preLoaderRoute: typeof BlogControleAsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/apr-digital': {
      id: '/blog/apr-digital'
      path: '/blog/apr-digital'
      fullPath: '/blog/apr-digital'
      preLoaderRoute: typeof BlogAprDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  FuncionalidadesRoute: FuncionalidadesRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SegurancaRoute: SegurancaRoute,
  TermosRoute: TermosRoute,
  BlogAprDigitalRoute: BlogAprDigitalRoute,
  BlogControleAsoRoute: BlogControleAsoRoute,
  BlogDdsDigitalRoute: BlogDdsDigitalRoute,
  BlogGestaoTreinamentosSstRoute: BlogGestaoTreinamentosSstRoute,
  BlogMobilizacaoTerceirosRoute: BlogMobilizacaoTerceirosRoute,
  BlogOrdemServicoSstRoute: BlogOrdemServicoSstRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
